version: '3'
services:
  app:
    build: .
    image: purchasesystem_app:latest
    user: appuser
    command: python -m uvicorn api.main:app --reload --host ${APP_HOST} --port ${APP_PORT}
    volumes:
      - .:/home/appuser
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}