FROM python:3.11-slim

ARG UID
ARG GID
ARG POETRY_VERSION

WORKDIR /src

RUN apt-get update \
 && apt-get install -y --no-install-recommends  \
 git libmagic-dev build-essential curl \
 && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=. \
    POETRY_VERSION=${POETRY_VERSION}

RUN pip install -U pip setuptools "poetry==$POETRY_VERSION"

COPY *.toml *.lock ./
RUN poetry config virtualenvs.create false

RUN poetry export --dev --with-credentials --without-hashes -f \
    requirements.txt --output requirements.txt && \
    pip install -r requirements.tx

COPY . /src

EXPOSE 8000

ENV PIP_EXTRA_INDEX_URL=""

RUN groupadd -r appgroup && useradd -r -g appgroup appuser
RUN chown -R appuser:appgroup /src

USER appuser
