FROM python:3.9

ARG UID
ARG GID

ENV PYTHONUNBUFFERED 1

RUN mkdir /tmp/requirements
COPY requirements/* /tmp/requirements/

RUN apt-get update && apt-get install -y --no-install-recommends \
  make python3-dev docker docker-compose build-essential apt-utils \
  curl python-openssl && apt-get -y autoremove
RUN pip install --upgrade pip && pip install -r /tmp/requirements/dev.txt

RUN groupadd -r -g "$GID" appuser; useradd -l --create-home -u "$UID" -g "$GID" appuser
WORKDIR /home/appuser
COPY . /home/appuser

USER appuser